apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  ports:
  - name: "24224"
    port: 24224
    targetPort: 24224
  - name: 24224-UDP
    port: 24224
    protocol: UDP
    targetPort: 24224
  selector:
    io.kompose.service: fluentd
status:
  loadBalancer: {}
